/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/GuitarAmp.glb --types -o src/components/amp/AmpModelGenerated.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial001: THREE.Mesh;
    defaultMaterial002: THREE.Mesh;
    defaultMaterial003: THREE.Mesh;
    defaultMaterial004: THREE.Mesh;
    defaultMaterial005: THREE.Mesh;
    defaultMaterial006: THREE.Mesh;
    defaultMaterial009: THREE.Mesh;
    Knob1: THREE.Mesh;
    Knob2: THREE.Mesh;
    Knob3: THREE.Mesh;
    Knob4: THREE.Mesh;
    Knob5: THREE.Mesh;
    Knob6: THREE.Mesh;
    Knob7: THREE.Mesh;
    Knob8: THREE.Mesh;
    Knob9: THREE.Mesh;
    Light001: THREE.Mesh;
    Power: THREE.Mesh;
    Stands: THREE.Mesh;
    Switch2: THREE.Mesh;
    Switch3: THREE.Mesh;
    SwitchPower: THREE.Mesh;
  };
  materials: {
    body_1: THREE.MeshStandardMaterial;
    corners: THREE.MeshStandardMaterial;
    detail_1: THREE.MeshStandardMaterial;
    screens_1: THREE.MeshStandardMaterial;
    wire_1: THREE.MeshStandardMaterial;
    handle: THREE.MeshStandardMaterial;
    switches_1: THREE.MeshStandardMaterial;
    knob_1: THREE.MeshStandardMaterial;
    knobs_2: THREE.MeshStandardMaterial;
    light: THREE.MeshStandardMaterial;
    input_j_1: THREE.MeshStandardMaterial;
    rubber_stands: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/GuitarAmp.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[41.389, -104.681, 189.942]} scale={100}>
        <mesh
          geometry={nodes.defaultMaterial001.geometry}
          material={materials.body_1}
        />
        <mesh
          geometry={nodes.defaultMaterial002.geometry}
          material={materials.corners}
        />
        <mesh
          geometry={nodes.defaultMaterial003.geometry}
          material={materials.detail_1}
        />
        <mesh
          geometry={nodes.defaultMaterial004.geometry}
          material={materials.screens_1}
        />
        <mesh
          geometry={nodes.defaultMaterial005.geometry}
          material={materials.wire_1}
        />
        <mesh
          geometry={nodes.defaultMaterial006.geometry}
          material={materials.handle}
        />
        <mesh
          geometry={nodes.defaultMaterial009.geometry}
          material={materials.switches_1}
        />
        <mesh geometry={nodes.Knob1.geometry} material={materials.knob_1} />
        <mesh geometry={nodes.Knob2.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob3.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob4.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob5.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob6.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob7.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob8.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Knob9.geometry} material={materials.knobs_2} />
        <mesh geometry={nodes.Light001.geometry} material={materials.light} />
        <mesh geometry={nodes.Power.geometry} material={materials.input_j_1} />
        <mesh
          geometry={nodes.Stands.geometry}
          material={materials.rubber_stands}
        />
        <mesh
          geometry={nodes.Switch2.geometry}
          material={materials.switches_1}
        />
        <mesh
          geometry={nodes.Switch3.geometry}
          material={materials.switches_1}
        />
        <mesh
          geometry={nodes.SwitchPower.geometry}
          material={materials.switches_1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/GuitarAmp.glb");
