/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/NeonTree.glb --types -o src/components/amp/NeonTreeGenerated.tsx 
Author: Kirkieb (https://sketchfab.com/kirkieo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neon-palm-tree-sign-f8366d37c75b4a92b784ffbb72f3900a
Title: Neon Palm Tree Sign
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    ['Butterfly_Bush_8bf9d5ea-bde1-48da-8210-ffa9d922408f']: THREE.MeshStandardMaterial
    ['Sonata_28_0f4f3201-ebe1-46fe-97a5-133aa3aaf8a8']: THREE.MeshPhysicalMaterial
    ['Sonata_3_f3084e0e-1c4a-447d-9cfd-6f11110831d9']: THREE.MeshPhysicalMaterial
    ['Sonata_5_82008ba2-51b4-48d3-8f93-1440fdcc0c75']: THREE.MeshPhysicalMaterial
    ['Sonata_9_2c03ab2d-c77c-42f5-a7d0-40c365fe9adb']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/NeonTree.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Butterfly_Bush_8bf9d5ea-bde1-48da-8210-ffa9d922408f']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Sonata_28_0f4f3201-ebe1-46fe-97a5-133aa3aaf8a8']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Sonata_3_f3084e0e-1c4a-447d-9cfd-6f11110831d9']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Sonata_5_82008ba2-51b4-48d3-8f93-1440fdcc0c75']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Sonata_9_2c03ab2d-c77c-42f5-a7d0-40c365fe9adb']} />
      </group>
    </group>
  )
}

useGLTF.preload('/NeonTree.glb')
